# Container with all prereqs to build ISCE
FROM nvidia/cuda:10.1-devel-ubuntu19.04

# build-required packages
RUN apt-get install -y \
    cmake \
    cython3 \
    fftw3-dev \
    git \
    libgdal-dev \
    libhdf5-dev \
    locales \
    python3-dev \
    python3-numpy
    #libhdf5-cpp-103

# set up locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
