# -*- coding: utf-8 -*-

import pyre

class ProductReader(pyre.protocol,
                    family='nisar.productreader'):
    '''
    Interface for reading standard products generated by NISAR.

    We use this interface to set up default paths within HDF5 file that need to parsed to set up various pieces of information.
    '''

    _CFPath = pyre.properties.str(default='/')
    _CFPath.doc = 'Absolute path to scan for CF convention metadata'

    _IdentificationPath = pyre.properties.str(default='/science/LSAR/identification')
    _IdentificationPath.doc = 'Absolute path ath to unique product identification information'

    _MetadataPath = pyre.properties.str(default='metadata')
    _MetadataPath.doc = 'Relative path to metadata associated with standard product'

    _SwathPath = pyre.properties.str(default='swaths')
    _SwathPath.doc = 'Relative path to swaths associated with standard product'

    _GridPath = pyre.properties.str(default='grids')
    _GridPath.doc = 'Relative path to grids associated with standard product'

    
    @pyre.provides
    def parse(self, hdf5file):
        '''
        Open and parse the user provided HDF5 file.
        '''

    @classmethod
    def pyre_default(cls, **kwds):
        '''
        Default product reader to return.
        '''
        from .. import SLC
        return SLC

