set(TESTFILES
antenna/edge_method_cost_func.cpp
antenna/frame.cpp
container/rsd.cpp
core/attitude/quaternion_euler.cpp
core/attitude/attitude.cpp
core/attitude/representations.cpp
core/datetime/datetime.cpp
core/ellipsoid/ellipsoid.cpp
core/interp1d.cpp
core/interpolator/interpolator.cpp
core/linspace/linspace.cpp
core/lut/lut1d.cpp
core/lut/lut2d.cpp
core/matrix/matrix.cpp
core/orbit/orbit.cpp
core/poly/poly1d.cpp
core/poly/poly2d.cpp
core/projections/cea.cpp
core/projections/geocent.cpp
core/projections/polar.cpp
core/projections/utm.cpp
core/serialization/serializeAttitude.cpp
core/serialization/serializeDoppler.cpp
core/serialization/serializeOrbit.cpp
fft/fft.cpp
fft/fftplan.cpp
fft/fftutil.cpp
focus/bistatic-delay.cpp
focus/chirp.cpp
focus/dry-troposphere-model.cpp
focus/gaps.cpp
focus/presum.cpp
focus/rangecomp.cpp
geocode/geocodeCov.cpp
geocode/geocodeSlc.cpp
geometry/dem/dem.cpp
geometry/geo2rdr/geo2rdr.cpp
geometry/geometry/geometry_constlat.cpp
geometry/geometry/geometry.cpp
geometry/geometry/geometry_equator.cpp
geometry/rtc/rtc.cpp
geometry/topo/topo.cpp
geometry/bbox/geoperimeter_equator.cpp
geometry/metadata_cubes/metadata_cubes.cpp
geogrid/relocate_raster.cpp
image/resampslc/resampslc.cpp
io/gdal/buffer.cpp
io/gdal/gdal-dataset.cpp
io/gdal/geotransform.cpp
io/gdal/spatialreference.cpp
io/IH5/ih5castread.cpp
io/IH5/ih5castwrite.cpp
io/IH5/ih5.cpp
io/IH5/ih5gdal.cpp
io/IH5/ih5nativeread.cpp
io/IH5/ih5nativewrite.cpp
io/raster/raster.cpp
io/raster/rasterepsg.cpp
io/raster/rastermatrix.cpp
io/raster/rasterview.cpp
math/bessel/bessel53.cpp
math/sinc.cpp
math/polyfunc.cpp
math/root_find1d.cpp
polsar/symmetrize.cpp
product/serialization/serializeProduct.cpp
product/serialization/serializeProductMetadata.cpp
product/radargrid/radargrid.cpp
signal/convolve.cpp
signal/crossmul.cpp
signal/crossmultiply.cpp
signal/decimate.cpp
signal/filter.cpp
signal/filter_data.cpp
signal/multilook.cpp
signal/nfft.cpp
signal/shift_signal.cpp
signal/signal.cpp
signal/signal_utils.cpp
unwrap/icu/icu.cpp
unwrap/phass/phass.cpp
)

#This is a temporary fix - since GDAL does not support
#expose virtualmemmap on OS X. This will be revisited
#when GDAL adds the functionality or we update to add
#preprocessor directives to handle this.
if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    LIST(APPEND TESTFILES io/gdal/gdal-raster.cpp)
endif()
