name: isce3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - backoff
  - cmake>=3.19
  - cxx-compiler
  - doxygen
  - eigen>=3.3
  - fftw>=3.3
  - gdal>=3.0,!=3.9.2
  - gmock>=1.10
  - gtest>=1.10
  - h5py>=3.5
  - hdf5>=1.10.2
  - libgdal-hdf5
  - libgdal-netcdf
  - mkdocs
  - mkdocs-material
  - ninja
  - numpy>=1.20,<2
  - pandas
  - pdoc
  - pyaps3>=0.3
  - pybind11>=2.6
  - pyre>=1.12.5
  - pysolid
  - pytest
  - python>=3.9
  - ruamel.yaml
  - scipy!=1.10.0
  - shapely>=1.8
  - snaphu>=0.4
  - yamale
