import argparse
import os

import h5py
import iscetest
import numpy as np
import numpy.testing as npt
from nisar.workflows import bandpass_insar, insar, prepare_insar_hdf5
from nisar.products.insar.product_paths import RIFGGroupsPaths
from nisar.workflows.insar_runconfig import InsarRunConfig
from nisar.workflows.persistence import Persistence


def test_bandpass_run():
    '''
    Check if bandpass_insar runs without crashing.
    '''
    # load yaml file
    test_yaml = os.path.join(iscetest.data, 'bandpass_test.yaml')
    with open(test_yaml) as fh_test_yaml:
        test_yaml = fh_test_yaml.read().replace('@ISCETEST@', iscetest.data).\
                replace('@TEST_OUTPUT@', 'rifg_bandpass.h5').\
                replace('@TEST_PRODUCT_TYPES@', 'RIFG')

    # Create CLI input namespace with yaml text instead of filepath
    args = argparse.Namespace(run_config_path=test_yaml, log_file=False)

    # Initialize runconfig object
    runconfig = InsarRunConfig(args)
    runconfig.geocode_common_arg_load()

    out_paths = prepare_insar_hdf5.run(runconfig.cfg)

    persist = Persistence('insar.log', restart=True)
    persist.run_steps['dense_offsets'] = False
    # input test data is missing mandatory metadata that
    # causes the test fail
    persist.run_steps['baseline'] = False
    persist.run_steps['solid_earth_tides'] = False
    insar.run(runconfig.cfg, out_paths, persist.run_steps)


def _decimate_mask(src_mask, bandpassed_samples, factor, blocksize=4):
    '''
    Decimate an in-memory mask and return the result, with the
    destination seeded by the verbatim copy that cp_h5_meta_data leaves
    behind in bandpass_insar.
    '''
    freq_path = '/science/LSAR/RSLC/swaths/frequencyA'
    mask_path = f'{freq_path}/inputDataExceptionMask'
    with h5py.File('src_mask.h5', 'w') as src_h5, \
         h5py.File('dst_mask.h5', 'w') as dst_h5:
        src_h5.create_dataset(mask_path, data=src_mask)
        dst_h5.create_dataset(mask_path, data=src_mask)
        bandpass_insar.decimate_input_data_exception_mask(
            src_h5, dst_h5, freq_path, bandpassed_samples, factor, blocksize)
        return dst_h5[mask_path][()]


def test_decimate_input_data_exception_mask():
    '''
    Check that the bandpassed inputDataExceptionMask ends up on the width
    the bandpassed SLC dictates, for the 8-bit and the 16-bit mask alike,
    and that OR-reducing each group of samples loses no set bit.
    '''
    factor = 2
    rng = np.random.default_rng(1234)

    # The 8-bit mask carries anomaly codes only; the 16-bit mask also
    # carries per-polarization validity bits in its high byte. Both are
    # aggregated the same way, by OR over every bit
    for dtype in (np.uint8, np.uint16):
        lines, samples = 9, 12
        bandpassed_samples = samples // factor
        src_mask = rng.integers(1, np.iinfo(dtype).max + 1,
                                (lines, samples)).astype(dtype)

        decimated = _decimate_mask(src_mask, bandpassed_samples, factor)

        assert decimated.shape == (lines, bandpassed_samples)
        assert decimated.dtype == dtype

        groups = src_mask.reshape(lines, bandpassed_samples, factor)
        npt.assert_array_equal(decimated, np.bitwise_or.reduce(groups, axis=2))

        # No bit set in a group may be lost, over the full width of the dtype
        assert np.all(decimated & groups[:, :, 0] == groups[:, :, 0])
        assert np.all(decimated & groups[:, :, 1] == groups[:, :, 1])

    # The high byte of a 16-bit mask survives even where only one of the
    # contributing samples has a validity bit set
    src_mask = np.array([[0x0100, 0x0200, 0x8000, 0x0002]], dtype=np.uint16)
    npt.assert_array_equal(_decimate_mask(src_mask, 2, 2),
                           np.array([[0x0300, 0x8002]], dtype=np.uint16))

    # The output width comes from the bandpassed SLC, not from the mask,
    # so a mask wider than the grid needs is truncated to the grid
    assert _decimate_mask(np.ones((4, 11), np.uint8), 4, 2).shape == (4, 4)

    # A mask already on the bandpassed grid is left alone
    src_mask = rng.integers(0, 256, (4, 6)).astype(np.uint8)
    npt.assert_array_equal(_decimate_mask(src_mask, 6, 1), src_mask)

    # A mask too narrow to cover the bandpassed grid is a hard error
    npt.assert_raises(ValueError, _decimate_mask,
                      np.ones((4, 7), np.uint8), 4, 2)


def test_bandpass_validate():
    '''
    Validate products generated by bandpass workflow.
    '''
    scratch_path = '.'

    # Instantiate RIFG object to avoid hard-coding pahs to RIFG datasets
    group_path = f'{RIFGGroupsPaths().SwathsPath}/frequencyA/interferogram/HH'
    with h5py.File(os.path.join(scratch_path, 'rifg_bandpass.h5'), 'r') as h_rifg:

        # check if phase of generated interferogram is sufficiently close to 0.
        igram = h_rifg[f'{group_path}/wrappedInterferogram'][()]
        coh = h_rifg[f'{group_path}/coherenceMagnitude'][()]

        npt.assert_allclose(np.nanmean(coh[3:-2, 3:-2]), 1, atol=2 * 1e-2)


if __name__ == "__main__":
    test_bandpass_run()
    test_decimate_input_data_exception_mask()
    test_bandpass_validate()
