set(SRCS
container/container.cpp
container/RadarGeometry.cpp
core/core.cpp
core/Constants.cpp
core/DateTime.cpp
core/Ellipsoid.cpp
core/Interp1d.cpp
core/Kernels.cpp
core/Linspace.cpp
core/LookSide.cpp
core/LUT1d.cpp
core/LUT2d.cpp
core/Orbit.cpp
core/TimeDelta.cpp
focus/Backproject.cpp
focus/DryTroposphereModel.cpp
focus/focus.cpp
geometry/geometry.cpp
geometry/DEMInterpolator.cpp
io/gdal/Dataset.cpp
io/gdal/GDALAccess.cpp
io/gdal/GDALDataType.cpp
io/gdal/gdal.cpp
io/gdal/Raster.cpp
io/Raster.cpp
io/io.cpp
signal/signal.cpp
signal/Covariance.cpp
product/product.cpp
product/RadarGridParameters.cpp
product/Swath.cpp
isce.cpp
)
